--- #YAML:1.0
name:               Net-MRT
version:            0.0302
abstract:           Perl extension for decoding RFC6396 Multi-Threaded Routing Toolkit
author:
    - MaxiM Basunov <maxim.basunov@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
