---
abstract: 'Perl extension for decoding MRT RAW data'
author:
  - 'MaxiM Basunov <maxim.basunov@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-MRT
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.01
